### ISSUE TITLE
关于中文字体的显示

### ISSUE THREAD

**Issue by zifan-zhang** [Zuttergutao/Typstdocs-Zh-CN-#1]
我也才刚开始学习Typst，请问为什么和你相同设置，而我的字体显示不是宋体？
<img width="890" alt="image" src="https://user-images.githubusercontent.com/62230992/229688854-90e1f00a-2cb4-453c-9781-17633f1bcd2f.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/62230992/229688957-a6feaaf5-f336-4898-b3f2-a15de25d8e3e.png">
前者是在我的mac上的显示效果，后者是你的显示效果。

**Comment by Zuttergutao** [comment]
是否能够显示设置的字体效果跟你电脑所带字体库有关，很明显你电脑并没有带SimSun的字体库。你可以使用自带的字体库并修改设置
![image](https://user-images.githubusercontent.com/40693240/229689871-8b65c97e-1459-4300-a25a-b19e85505f48.png)

参见如下链接：https://zhuanlan.zhihu.com/p/139652407

**Comment by zifan-zhang** [comment]
谢谢，解决了，本地编译运行显示是ok的，只是web app需要手动上传字体文件。期待作者继续翻译更新中文文档。

**Comment by Zuttergutao** [comment]
谢谢支持，同时官网已推出v0.1的正式版本，对于中文排版有了很大的支持，但是好像还不支持斜体，加粗。
