### ISSUE TITLE
非官方 Typst 中文文档网站

### ISSUE THREAD

**Issue by OrangeX4** [Zuttergutao/Typstdocs-Zh-CN-#3]
我基于 Typst 的源码生成了与 Typst 官网样式一致的文档网站, 并基于此制作了中文文档.

并且我也写了一个 GitHub Action, 可以很简单地通过修改原来的 Markdown 文件进行翻译, 只需要 Push 到 main 分支就能通过持续集成部署到 GitHub Pages 上.

现在这个项目放到了 [typst-doc-cn](https://github.com/typst-doc-cn) 里, 希望能够借助开源社区的力量进行翻译.

有没有兴趣一起参与 Typst 文档的翻译呢?

非官方 Typst 中文文档网站
URL: https://typst-doc-cn.github.io/docs/
Repo: https://github.com/typst-doc-cn/typst-doc-cn.github.io

![image](https://github.com/Zuttergutao/Typstdocs-Zh-CN-/assets/34951714/039033c7-9090-4da2-b683-63f4de8dcb81)

**Comment by Zuttergutao** [comment]
当然了，荣幸之至。另外我创建了一个typst非官方交流群，目前来说交流还算活跃的，也有很多大佬在给typst做贡献，不知是否有兴趣加入？如果方便的话，可以加我微信：15852968531

**Comment by OrangeX4** [comment]
好的，我看看。之前没加是因为 typst-cn 的那个二维码已经过期了。
